version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8
        environment:
          NODE_ENV: test
      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_DB: rentmonitor_test
          POSTGRES_PASSWORD: rentmonitor
          POSTGRES_USER: rentmonitor_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}-
            - npm-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run build
      - run:
          name: Resetup test database
          command: npm run migrate -- --rebuild
      - run: npm run test
