version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: rentmonitor_test
          POSTGRES_DB: rentmonitor_test
          POSTGRES_PASSWORD: rentmonitor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}-
            - npm-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run build
      - run:
          name: Resetup test database
          command: npm run migrate -- --rebuild
      - run: npm run test
